# Generated by Django 6.0.4 on 2026-04-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('uzs', 'UZS'), ('rub', 'RUB')], default='usd', max_length=3),
        ),
    ]
